# デバック用

# デバック用の情報を可視化するかの設定用
# trueなら可視化
visualize_current_people_poses: true           # 歩行者の現在位置（odom）
visualize_selected_current_people_poses: true  # ロボットに近い歩行者の現在位置（base_footprint）
visualize_future_people_poses: true            # 歩行者の将来位置（予測）

# 歩行者の移動先予測をするかの変更用
# trueならロボットとの相対速度に応じて移動先予測
# falseなら現在の情報をfuture_pedとして渡す
flag_prediction: true
# flag_prediction: false


# 制御周波数[Hz]
hz: 10                          # ループ周波数 [Hz]

# frame_id
sim_frame: "odom"               # シミュレーター
robot_frame: "odom"             # ロボット
people_frame: "base_footprint"  # 歩行者

# 予測範囲
consider_dist_border: 8.0       # cost_map_createrにデータを渡す歩行者の距離 [m]
predict_dist_border: 3.0        # 歩行者の将来位置を予測する距離 [m]