# デバック用

# デバック用の情報を可視化するかの設定用
# trueなら可視化
# visualize_current_people_poses: true  # 歩行者の現在位置
# visualize_future_people_poses: true   # 歩行者の将来位置（予測）

# 制御周波数[Hz]
hz: 10              # ループ周波数 [Hz]

# frame_id
people_frame: "base_footprint"     # 歩行者
cost_map_frame: "baase_footprint"  # コストマップ
# robot_frame: "odom"   # ロボット
# people_frame: "odom"  # 歩行者

# map
map_size: 5.0    # マップの一辺の長さ [m]
map_reso: 0.025  # マップの解像度 [m/cell]

# 楕円のサイズ
ellipse_front_long_max: 1.0  # 楕円の長軸（歩行者の進行方向前方）の最大値 [m]
ellipse_back_long_max: 0.5   # 楕円の長軸（歩行者の進行方向後方）の最大値 [m]
ellipse_short_max: 0.5       # 楕円の短軸の最大値 [m]

# 楕円のサイズを決める際の重み定数（2つの合計が1になるように設定する）
weight_distance: 0.5         # ロボットからの距離に関する項
weight_velocity: 0.5         # 歩行者の速さに関する項

# 歩行者関連
ped_speed_max: 1.5           # 歩く速さの最大値 [m/s]

# コストマップ
min_cost: 10                 # 割り当てるコストの最小値

# 予測範囲
# predict_dist_border: 8.0  # 歩行者の将来位置を予測する距離 [m]
# predict_dist_resolution: 2.5  # 1秒先を予測する距離 [m]
