# デバック用

# 走行コストの設定をするかの設定用
# trueなら走行コストを設定
# falseなら障害物を膨張するのみ
flag_cost: true
# flag_cost: false

# 制御周波数[Hz]
hz: 12              # ループ周波数 [Hz]

# frame_id
people_frame: "base_footprint"     # 歩行者
cost_map_frame: "base_footprint"  # コストマップ

# map
map_size: 5.0    # マップの一辺の長さ [m]
map_reso: 0.05  # マップの解像度 [m/cell]

# 楕円のサイズ
ellipse_front_long_max: 1.5  # 楕円の長軸（歩行者の進行方向前方）の最大値 [m]
ellipse_front_long_min: 0.5  # 楕円の長軸（歩行者の進行方向前方）の最小値 [m]
ellipse_back_long_max: 1.0   # 楕円の長軸（歩行者の進行方向後方）の最大値 [m]
ellipse_back_long_min: 0.3   # 楕円の長軸（歩行者の進行方向後方）の最小値 [m]
ellipse_short_max: 1.0       # 楕円の短軸の最大値 [m]
ellipse_short_min: 0.3       # 楕円の短軸の最小値 [m]

# 衝突半径
margin: 0.5                  # 人間の肩幅＋ccvの幅の半分 [m]

# 楕円のサイズを決める際の重み定数（2つの合計が1になるように設定する）
weight_distance: 0.5         # ロボットからの距離に関する項
weight_velocity: 0.5         # 歩行者の速さに関する項

# 歩行者関連
ped_speed_max: 1.5           # 歩く速さの最大値 [m/s]

# コストマップ
count_reso: 0.02             # コストを割り当てる際に計算する座標の刻み幅 [m]
min_cost: 50.0               # 割り当てるコストの最小値